apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: marksync

resources:
  - namespace.yaml
  - storage.yaml
  - configmap.yaml
  - sync-server.yaml
  - dashboard.yaml
  - orchestrator.yaml
