apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-pvc
  namespace: marksync
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
